#if !canImport(ObjectiveC)
import XCTest

extension EddystoneScannerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EddystoneScannerTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EddystoneScannerTests.__allTests__EddystoneScannerTests),
    ]
}
#endif
